export const tokenTypes = {
    comment: 'token-type--comment',
    codeBlockStart: 'token-type--code-block-start',
    codeBlockEnd: 'token-type--code-block-end',
    semicolon: 'token-type--semicolon',
    comma: 'token-type--comma',
    colon: 'token-type--colon',
    bracketOpen: 'token-type--bracket-open',
    bracketClose: 'token-type--bracket-close',
    squareBracketOpen: 'token-type--square-bracket-open',
    squareBracketClose: 'token-type--square-bracket-close',
    equals: 'token-type--equals',
    number: 'token-type--number',
    string: 'token-type--string',
    word: 'token-type--word',
    cr: 'token-type--cr',
    lf: 'token-type--lf',
    mathPlus: 'tokentype--math-plus',
    mathMinus: 'tokentype--math-minus',
    mathMul: 'tokentype--math-mul',
    mathDiv: 'tokentype--math-div',
    mathMod: 'tokentype--math-mod',
    mathPow: 'tokentype--math-pow'
};