export const tokenTypes = {
    comment: 'token-type--comment',
    codeBlockStart: 'token-type--code-block-start',
    codeBlockEnd: 'token-type--code-block-end',
    semicolon: 'token-type--semicolon',
    comma: 'token-type--comma',
    colon: 'token-type--colon',
    bracketOpen: 'token-type--bracket-open',
    bracketClose: 'token-type--bracket-close',
    squareBracketOpen: 'token-type--square-bracket-open',
    squareBracketClose: 'token-type--square-bracket-close',
    equals: 'token-type--equals',
    integer: 'token-type--integer',
    float: 'token-type--float',
    string: 'token-type--string',
    word: 'token-type--word',
    whitespace: 'token-type--whitespace',
    newline: 'token-type--newline',
    mathOp: 'tokentype--math-op'
};